name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      uses: nuget/setup-nuget@v1
      with:
        dotnet-version: 5.0.100
        nuget-api-key: ${{ secrets.NUGET_TOKEN }}
        nuget-version: '5.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Sign Package
      run: echo Test